build:
    maxIssues: 0

config:
    validation: true

complexity:
    LongMethod:
        excludes:
            - '**/test/**'
    LongParameterList:
        excludes:
            - '**/test/**'
    TooManyFunctions:
        excludes:
            - '**/test/**'
            - '**/DesignTokenHoverPopupPanel.kt'

style:
    MagicNumber:
        active: false
    MaxLineLength:
        active: false
