build:
    maxIssues: 0

config:
    validation: true

complexity:
    TooManyFunctions:
        excludes: ['**/DesignTokenHoverPopupPanel.kt']

style:
    MagicNumber:
        active: false
    MaxLineLength:
        active: false
